### ISSUE TITLE
Contract Error Trying to Get MFT for Testing

### ISSUE THREAD

**Issue by eolszewski** [MainframeHQ/onyx#77]
It also costs 7.6 Million gas to try and get one MFT to stake - is this expected behavior?

![screen shot 2018-06-18 at 10 14 38 am](https://user-images.githubusercontent.com/3613197/41545387-aa76605a-72e0-11e8-8763-8835952a8743.png)

**Comment by dleonard00** [comment]
Definitely, unexpected. We will dig into this.

**Comment by howleysv** [comment]
It looks like some issue with gas estimation in metamask when the tx is going to fail. Perhaps due to the [dynamic call](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.10.0/contracts/token/ERC827/ERC827Token.sol#L51) using when staking MFT?

With good inputs (using wallet that has >1 MFT balance) it makes a more reasonable estimate
![screen shot 2018-06-19 at 11 29 58](https://user-images.githubusercontent.com/4747933/41592745-8550f62a-73b5-11e8-97a8-252d933b9c70.png)

[Here](https://etherscan.io/tx/0x7485f298b92793a3a15fb63a818a29e7b9bc0cd086462227f89f19281f133629) is an example of a successful tx.


The real issue here is that there are no MFT tokens to use with this right now. The tokens should be more readily available after distribution which is scheduled for July 4.
